# Generated by Django 2.2 on 2020-05-15 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('localizacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('telefono', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('ejemplares', models.ManyToManyField(to='ejbiblioteca.Ejemplar')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('titulo', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('paginas', models.IntegerField()),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ejbiblioteca.Autor')),
            ],
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ejbiblioteca.Libro'),
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='usuarios',
            field=models.ManyToManyField(to='ejbiblioteca.Usuario'),
        ),
    ]
